package telegram

import "github.com/stretchr/testify/mock"

// This is an autogenerated mock type for the Request type
type MockRequest struct {
	mock.Mock
}

// Call provides a mock function with given fields: method, in
func (_m *MockRequest) Call(method string, in interface{}) (*Response, error) {
	ret := _m.Called(method, in)

	var r0 *Response
	if rf, ok := ret.Get(0).(func(string, interface{}) *Response); ok {
		r0 = rf(method, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(method, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
